[runner]
program = "roblox-cli"
args = "run --load.model ${Project} --run ${Benchmark} --headlessRenderer 1 --fastFlags.overrides \"DebugScriptProfilerEnabled=true\" --lua.globals=__OTTER_MOCK_HEARTBEAT__=true ${Dev} "
dev = "--lua.globals=__DEV__=true"

[project]
file-glob = "benchmarks/**/*.lua"

[results]
output-pattern = "${Total}ms - ${Step}µs"

Total.type = "sum"
Step.type = "average"

Total.suffix = "ms"
Step.suffix = "µs"
