[runner]
program = "robloxdev-cli"
args = "run --load.model ${Project} --run ${Benchmark} --headlessRenderer 1 ${Flags} ${Globals} --fastFlags.allOnLuau ${DevArgs}"
flags = "DebugScriptProfilerEnabled=true"
globals = "__OTTER_MOCK_HEARTBEAT__=true"
devArgs = ""
devFlags = ""
devGlobals = "__DEV__=true"

[project]
file-glob = "benchmarks/**/*.lua"

[results]
output-pattern = "${Metric} ${Value}ms - ${Step}µs"

Metric.type = "static"
Value.type = "sum"
Step.type = "average"
