site_name: Otter Documentation
site_url: https://roblox.github.io/otter-internal/
repo_name: Roblox/otter-internal
repo_url: https://github.com/Roblox/otter-internal

theme:
  name: material
  palette:
    primary: "Light Blue"
    accent: "Light Blue"

nav:
  - Home: index.md
  - Usage:
      - Motors: usage/motors.md
      - Goals: usage/goals.md
      - React: usage/react.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
