[package]
name = "Otter"
authors = ["Roblox"]
license = "MIT/Apache-2.0"
content_root = "lib"
version = "0.1.6"
files = ["*", "!*.spec.lua"]

[dev_dependencies]
TestEZ = "github.com/Roblox/testez@0.4.1"
