[package]
name = "ReactOtter"
version = "1.0.0"
authors = ["Roblox"]
license = "MIT/Apache-2.0"
content_root = "src"
files = ["*", "!*.spec.lua", "!jest.config.lua"]

[dependencies]
Otter = { path = "../otter" }
React = "github.com/roblox/roact-alignment@17.0.1-rc.18"

[dev_dependencies]
ReactTestingLibrary = "github.com/roblox/react-testing-library-lua@12.1.5"
Jest = "github.com/Roblox/jest-roblox@3.2.5"
JestGlobals = "github.com/Roblox/jest-roblox@3.2.5"

# used for storybook
RoactCompat = "github.com/roblox/roact-alignment@17.0.1-rc.18"
