[package]
name = "Otter"
version = { workspace = true }
authors = ["Roblox"]
license = "MIT/Apache-2.0"
content_root = "src"
files = ["*", "!*.spec.lua", "!**/__tests__/**"]

[dependencies]
Collections = "github.com/roblox/luau-polyfill@1.2.2"
Signal = "github.com/roblox/signal-lua@1.0"

[dev_dependencies]
Jest = "github.com/Roblox/jest-roblox@3.2.5"
JestGlobals = "github.com/Roblox/jest-roblox@3.2.5"
