[package]
name = "OtterBenchmarks"
version = { workspace = true }
authors = ["Roblox"]
publish = false
license = "MIT"
content_root = "src"

[dependencies]
Otter = { path = "../otter" }
ReactOtter = { path = "../react-otter" }

Roact = "github.com/roblox/roact@1.4.3"

React = "github.com/roblox/roact-alignment@17.0.1-rc.18"
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.18"
