name: Composite Publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: "The package to publish. Defaults to publishing the entire workspace"
        required: false
        type: string
      ref:
        description: "The ref (tag, branch, commit id, etc) of package to publish (defaults to main/master)"
        required: false
        type: string

jobs:
  composite-publish:
    runs-on: [self-hosted, generic-linux]
    container:
      image: docker.artifactory.rbx.com/rbx-lua-build-tools:latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate access token
        uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}

      - name: Get foreman and run foreman install
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ steps.setup_token.outputs.token }}

      - name: Composite Publish
        uses: Roblox/rotriever-registry-workflows/composite-publish@v1
        with:
          ref: ${{ github.event.inputs.ref }}
          artifactory-token: ${{ secrets.ROBLOX_ARTIFACTORY_CI_PUBLISH_BEARER_TOKEN }}
          github-token: ${{ steps.setup_token.outputs.token }}
          package: ${{ github.event.inputs.package }}
